name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build backend
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload jar to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 217.154.181.154
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "target/TFG_DAW-0.0.1-SNAPSHOT.jar"
          target: "/root/back/"

      - name: Restart backend on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 217.154.181.154
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Stopping old backend..."
      
            PID=$(pgrep -f TFG_DAW-0.0.1-SNAPSHOT.jar || true)
      
            if [ ! -z "$PID" ]; then
              echo "Killing process $PID"
              kill -9 $PID
            else
              echo "No backend running"
            fi
      
            echo "Starting new backend..."
      
            cd /root/back/target
      
            nohup java -Djava.net.preferIPv4Stack=true -jar TFG_DAW-0.0.1-SNAPSHOT.jar \
            > /root/back/nohup.out 2>&1 &
      
            sleep 6
      
            echo "Running processes:"
            ps aux | grep java
      
            echo "Port check:"
            lsof -i :9012 || true
